url: https://dtbngoc.github.io
baseurl:

# Site settings
title: My Portfolio
email: dangtb.ngoc@gmail.com
description: "Dang Ngoc's portfolio where I showcase my exceptional design skills"


# Team names, titles and social links
people:
- name: Đặng Thị Bích Ngọc
  pic: 1
  position: UI/UX Designer
  social:
    - title: instagram
      url: https://www.instagram.com/binnae.dae/
    - title: facebook
      url: https://www.fb.com/binnae.dae/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:https://www.fb.com/binnae.dae/
  - title: github
    url: http://github.com/dtbngoc

# Postal address (add as many lines as necessary)
address:
  - line: Ho Chi Minh City
  - line: Viet Nam 700000

# Build settings
markdown: kramdown
permalink: pretty
